name: flutter_camera_overlay
description: A Flutter plugin to add common camera overlay components such as ID Card, Credit Card, Texts, prompts or custom components.
version: 0.1.1
homepage: https://github.com/KiritoDv/flutter_camera_overlay
repository: https://github.com/KiritoDv/flutter_camera_overlay
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  
flutter:
  uses-material-design: true
